version: '3.8'
services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.external-url=/prometheus/
            - --web.route-prefix=/prometheus/
        volumes:
            - ./prometheus/:/etc/prometheus:ro
            - prometheus_data:/prometheus
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        depends_on:
            - cadvisor
            - node_exporter
        networks:
            - 'nginx'
    alertmanager:
        image: prom/alertmanager:latest
        container_name: alertmanager
        restart: unless-stopped
        volumes:
            - ./alertmanager/:/etc/alertmanager:ro
        command:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--web.external-url=https://kyleslab.net:9093'
        networks:
            - 'nginx'
    cadvisor:
        image: google/cadvisor:latest
        privileged: true
        container_name: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        restart: unless-stopped
        networks:
            - 'nginx'
    node_exporter:
        image: prom/node-exporter:latest
        container_name: node_exporter
        command:
            - '--path.rootfs=/host'
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana:/usr/config/grafana
        depends_on:
            - prometheus
        env_file:
            - ./.env
        restart: unless-stopped
        networks:
            - 'nginx'
volumes:
    prometheus_data: {}
    grafana_data: {}
networks:
    nginx:
        external:
            name: nginx_reverse_proxy