#global config
global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:     10s
  #query_log_file: <string>
  external_labels:
    monitor: 'codelab-monitor'
alerting:
  alertmanagers:
  - static_configs:
      - targets: ['alertmanager:9093']
rule_files:
  - alert.yml
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
      labels:
        alias: 'prometheus'
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        alias: 'cadvisor'
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['host.docker.internal:9100']
      labels:
        alias: 'node_exporter'